### ISSUE TITLE
div with v-katex directive not displaying.

### ISSUE THREAD

**Issue by aaronjylee** [haoranyu/Vue-KaTeX-Auto-render#1]
I followed the installation process by installing through npm and adding it in my `main.js` file:

![image](https://user-images.githubusercontent.com/1317273/89333240-8d4fdf00-d649-11ea-8371-01eb8cc995da.png)

In one of my components, I added a div with the `v-katex` directive to test it out:

![image](https://user-images.githubusercontent.com/1317273/89333299-a062af00-d649-11ea-9e5e-0ed2c61385c5.png)

When I go to the site, I don't see any element displayed, but in the dev tools I see that the div exists:

![image](https://user-images.githubusercontent.com/1317273/89333438-cf792080-d649-11ea-895b-8f5a20335eb2.png)

I am using Vue 2.6.11.

**Comment by haoranyu** [comment]
I'm sorry for not getting back to you in time.

It seems to be the problem of css loading.

Can you please try to integrate css separately by

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
``` 

Or you may add the css loader support in Vue according to https://vue-loader.vuejs.org/guide/css-modules.html
